language: go

go:
  - 1.12.x
  
os:
  - linux
  - osx

script:
  - go test -race -coverprofile=coverage.txt $(go list ./... | grep -v '/simulation' | grep -v mock | grep -v 'netcloth-chain/tests' | grep -v crypto)

after_success:
  - bash <(curl -s https://codecov.io/bash)