language: go

go:
  - 1.12.x
  
os:
  - linux
  - osx

script:
  - env GO111MODULE=on make

install:
  - pip install coverage
  - pip install codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)