language: go

go:
  - 1.12.x
  
os:
  - linux
  - osx

script:
  - env GO111MODULE=on make

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"